google_analytics: G-PKXJ59Y704

header_pages:
 - index.md
 - compilers-basics.md

style: light

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-remote-theme

kramdown:
  math_engine: katex
  math_engine_opts:
    output: mathml
    displayMode: false
  syntax_highlighter: rouge
  input: GFM

remote_theme: b2a3e8/jekyll-theme-console
