google_analytics: G-PKXJ59Y704

header_pages:
 - index.md
 - compilers-basics.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: light

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console